### ISSUE TITLE
error on make install

### ISSUE THREAD

**Issue by hatsch** [ob-encoder/obe-rt#1]
hi every body,

i've followed the installation guide for 
http://obe.wikia.com/wiki/Open_Broadcast_Encoder_Wiki#Realtime_Guides

compiling is just fine, only the make install command brings the following error:

install -d /usr/bin
install -d /usr/include
install -d /usr/lib
install -d /usr/lib/pkgconfig
install -m 644 libobe.a /usr/lib
install -m 644 obe.pc /usr/lib/pkgconfig
install: cannot stat `obe.pc': No such file or directory
make: **\* [install] Error 1

the obecli programm is in the src directory and is executable and working. at least probing the decklink input works. i wasn't able to generate a stream yet, due my lack in understanding the required options (specially the TARGET option) but thats another issue ;)

i would love to bring that tool to work! so any help is really appreciated

thanks alot 
ste

**Comment by kierank** [comment]
(sorry for the late reply - this report doesn't appear on my github feed for some reason)

This has been fixed in the development tree.
